const ActionTypes = {
    PRODUCT_LOADİNG: "PRODUCT_LOADİNG",
    PRODUCT_SUCCESS: "PRODUCT_SUCCESS",
    PRODUCT_ERROR: "PRODUCT_ERROR",
    REST_LOADİNG: "REST_LOADİNG",
    REST_SUCCESS: " REST_SUCCESS",
    REST_ERROR: "REST_ERROR",
    ADD_TO_CART: "ADD_TO_CART",
    UPDATE_CART: "UPDATE_CART",
    ERROR_CART: "ERROR_CART",
    DELETE_FROM_CART: "DELETE_FROM_CART",
};

export default ActionTypes;